[project]
name = "face-auth-model"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "flask>=3.1.2",
    "insightface>=0.7.3",
    "numpy>=2.0.2",
    "onnxruntime>=1.20.1",
    "opencv-python>=4.11.0.86",
]
