[project]
name = "face-auth-model"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "insightface>=0.7.3",
    "numpy>=2.2,<2.3",
    "onnxruntime>=1.23.2",
    "opencv-python-headless>=4.12.0.88",
]
